/**
 * Revue croisée des traductions : ce qui se vérifie sans lire la langue.
 *
 * `check:translations` compare les clés. Il ne voit ni une variable
 * `{{model}}` perdue en route, ni une balise `<1>` disparue d'un composant
 * `Trans`, ni un texte vide : trois défauts qui s'affichent tels quels à
 * l'écran. Ceux-là sont des erreurs.
 *
 * Un texte identique à l'anglais n'est pas une erreur — un nom de modèle ou
 * « Cmd+Enter » ne se traduisent pas — mais c'est souvent une section jamais
 * traduite. Il est listé par langue, sauf pour les clés gardées exprès.
 */

export type ReviewErrorKind = "placeholder" | "tag" | "empty";

export interface ReviewError {
  key: string;
  kind: ReviewErrorKind;
  expected: string[];
  found: string[];
}

export interface LanguageReview {
  errors: ReviewError[];
  untranslated: string[];
}

type Tree = { [key: string]: unknown };

const PLACEHOLDER = /\{\{\s*([^}\s]+)\s*\}\}/g;
const TAG = /<\/?([A-Za-z0-9]+)[^>]*>/g;
// Un mot d'au moins quatre lettres : « 12:00 », « p95 » ou « OK » ne
// suffisent pas à dire qu'un texte est resté en anglais.
const WORD = /[A-Za-z]{4,}/;

/** Les clés imbriquées deviennent des chemins pointés, dans l'ordre du fichier. */
export function flatten(tree: Tree, prefix = ""): Map<string, string> {
  const found = new Map<string, string>();
  for (const [key, node] of Object.entries(tree)) {
    const path = prefix ? `${prefix}.${key}` : key;
    if (typeof node === "string") {
      found.set(path, node);
    } else if (
      node !== null &&
      typeof node === "object" &&
      !Array.isArray(node)
    ) {
      for (const [nested, value] of flatten(node as Tree, path))
        found.set(nested, value);
    }
  }
  return found;
}

export function placeholdersOf(text: string): string[] {
  return [...text.matchAll(PLACEHOLDER)].map((match) => match[1]).sort();
}

export function tagsOf(text: string): string[] {
  return [...text.matchAll(TAG)].map((match) => match[1]).sort();
}

function sameList(left: string[], right: string[]): boolean {
  return (
    left.length === right.length &&
    left.every((item, index) => item === right[index])
  );
}

function hasWords(text: string): boolean {
  return WORD.test(text.replace(PLACEHOLDER, " ").replace(TAG, " "));
}

/**
 * Une langue relue contre la référence.
 *
 * Une clé absente de la traduction n'est pas relue ici : `check:translations`
 * la signale déjà, et la compter deux fois brouillerait le rapport.
 */
export function reviewLanguage(
  reference: Map<string, string>,
  translation: Map<string, string>,
  keep: Set<string>,
): LanguageReview {
  const errors: ReviewError[] = [];
  const untranslated: string[] = [];
  for (const [key, source] of reference) {
    const text = translation.get(key);
    if (text === undefined) continue;
    if (text.trim() === "") {
      errors.push({ key, kind: "empty", expected: [], found: [] });
      continue;
    }
    const expectedPlaceholders = placeholdersOf(source);
    const foundPlaceholders = placeholdersOf(text);
    if (!sameList(expectedPlaceholders, foundPlaceholders)) {
      errors.push({
        key,
        kind: "placeholder",
        expected: expectedPlaceholders,
        found: foundPlaceholders,
      });
    }
    const expectedTags = tagsOf(source);
    const foundTags = tagsOf(text);
    if (!sameList(expectedTags, foundTags)) {
      errors.push({
        key,
        kind: "tag",
        expected: expectedTags,
        found: foundTags,
      });
    }
    if (text === source && hasWords(source) && !keep.has(key))
      untranslated.push(key);
  }
  return { errors, untranslated };
}

function describeError(error: ReviewError): string {
  const list = (items: string[]) =>
    items.length === 0
      ? "none"
      : items
          .map((item) =>
            error.kind === "placeholder" ? `\`{{${item}}}\`` : `\`<${item}>\``,
          )
          .join(", ");
  if (error.kind === "empty") return `\`${error.key}\` — empty text`;
  return `\`${error.key}\` — ${error.kind}: expected ${list(error.expected)}, found ${list(error.found)}`;
}

/** Le rapport par langue : un tableau de synthèse, puis le détail à corriger. */
export function formatReport(results: Record<string, LanguageReview>): string {
  const locales = Object.keys(results).sort();
  const lines = [
    "# Translation review",
    "",
    "Generated by `bun run review:translations`. Every language is compared with English.",
    "",
    "- **Broken**: a `{{variable}}` or a tag missing or renamed, or an empty text. These break the interface and fail the check.",
    "- **Left in English**: text identical to English. Names kept on purpose are listed in `src/i18n/kept-in-english.json` and not counted.",
    "",
    "| Language | Broken | Left in English |",
    "| --- | --- | --- |",
    ...locales.map(
      (locale) =>
        `| ${locale} | ${results[locale].errors.length} | ${results[locale].untranslated.length} |`,
    ),
  ];
  for (const locale of locales) {
    const { errors, untranslated } = results[locale];
    if (errors.length === 0 && untranslated.length === 0) continue;
    lines.push("", `## ${locale}`);
    if (errors.length > 0) {
      lines.push(
        "",
        "### Broken",
        "",
        ...errors.map((error) => `- ${describeError(error)}`),
      );
    }
    if (untranslated.length > 0) {
      lines.push(
        "",
        "### Left in English",
        "",
        ...untranslated.map((key) => `- \`${key}\``),
      );
    }
  }
  return `${lines.join("\n")}\n`;
}

/** Les motifs du fichier des noms gardés en anglais : `*` vaut un segment. */
export function expandKeptKeys(
  patterns: string[],
  keys: Iterable<string>,
): Set<string> {
  const matchers = patterns.map(
    (pattern) =>
      new RegExp(
        `^${pattern
          .split("*")
          .map((part) => part.replace(/[.+?^${}()|[\]\\]/g, "\\$&"))
          .join("[^.]+")}$`,
      ),
  );
  return new Set(
    [...keys].filter((key) => matchers.some((matcher) => matcher.test(key))),
  );
}
